/**
 * 加点规则，比如注册，订单Pay
 * @Autor duanjunwei 
 * @Created at 06/03 2016
 */
package rules.point;
import com.genscript.gsscm.rules.point.fact.PointFact;

dialect  "mvel"

rule "register new customer account" 
    //注册新用户，加点1000积分
    salience 300
    lock-on-active true  
    when
        $p : PointFact( actionType == "register" )
    then
        $p.points = 1000;
        $p.comments  = "Welcome VIP points";
               
        System.out.println("register new customer account: add " + $p.points);
end

rule "pay for an order" 
    //订单支付加点，1$对应1 point
    salience 299
    lock-on-active true  
    when
        $p : PointFact( actionType == "payment", 
                        amount != null && amount > 0 )
    then
        $p.points = (int)$p.amount;
        $p.comments  = "Points from order";
               
        System.out.println("pay for an order: add " + $p.points);
end

